# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "905bb0eed902d4df978cc4e0705dffbf"
name = "DiscountJet"
application_url = "https://bone-daisy-surrounded-voting.trycloudflare.com/shopify/install"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "discounts/create",
  "discounts/update",
  "discounts/delete"
]
  uri = "https://bone-daisy-surrounded-voting.trycloudflare.com/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_discounts,read_orders,read_price_rules,read_products,write_cart_transforms,write_discounts,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://bone-daisy-surrounded-voting.trycloudflare.com/shopify/callback"
]
